\i steps/hyper.sql
\i steps/append.sql
\i steps/uncompress.sql
\i steps/compress.sql
\i steps/append.sql
\i steps/rename_column.sql
\i steps/rename_column.sql
\i steps/rename_column.sql
\i steps/rename_column.sql
\i steps/rename_column.sql
\i steps/append.sql
\i steps/add_column_nullable.sql
\i steps/add_column_default.sql
\i steps/uncompress.sql
\i steps/compress.sql
