\i hyper.sql
\i append.sql
\i uncompress.sql
\i compress.sql
\i append.sql
\i rename_column.sql
\i rename_column.sql
\i rename_column.sql
\i rename_column.sql
\i rename_column.sql
\i append.sql
\i add_column_nullable.sql
\i add_column_default.sql
\i uncompress.sql
\i compress.sql
